#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  # push:
  # pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:

  duckdb-stable-build:
    if: false # disable stable builds for now
    name: Build stable extension binaries
    # uses: ./.github/workflows/_extension_distribution.yml
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.3.2
    with:
      duckdb_version: v1.3.2
      ci_tools_version: v1.3.2
      extension_name: nanodbc
      exclude_archs: 'linux_amd64_musl;osx_amd64;wasm_mvp;wasm_eh;wasm_threads;'
  #     exclude_archs: 'linux_amd64;linux_arm64;linux_amd64_musl;osx_amd64;wasm_mvp;wasm_eh;wasm_threads;windows_amd64_mingw'

  duckdb-next-build:
    name: Build main extension binaries
    # uses: ./.github/workflows/_extension_distribution.yml
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    with:
      duckdb_version: v1.4-andium
      ci_tools_version: main
      extension_name: nanodbc
      exclude_archs: 'linux_amd64_musl;osx_amd64;wasm_mvp;wasm_eh;wasm_threads;'
